### ISSUE TITLE
Full mode error

### ISSUE THREAD

**Issue by sa-boh** [SRMLabHUST/LuckyProfiler#1]
hello, thanks for sharing your code.
I used your code to test our result's resolution; for running in ROI mode there is no problem (however with a huge difference between gaussian and deconvolution fitting methods), but when I switch to full mode I get this error:
Exception in thread "Thread-6" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at LuckyProfileRunner.How2FWHM2Auto(LuckyProfiler_.java:565)
	at LuckyProfileRunner.run(LuckyProfiler_.java:307)

could you help me pls with this? I tried different images and both Fiji and ImageJ but got the same error!

**Comment by Hpsoyl** [comment]
Have u solved this? I met this question too!
