### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bsdgc** [SRMLabHUST/LuckyProfiler#2]
Hi, Thanks for sharing this helpful code. If I change the pix size, I will get the following error:

Exception in thread "Thread-7" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\median_blur.dispatch.cpp:285: error: (-215:Assertion failed) (ksize % 2 == 1) && (_src0.dims() <= 2 ) in function 'cv::medianBlur'
]
	at org.opencv.imgproc.Imgproc.medianBlur_0(Native Method)
	at org.opencv.imgproc.Imgproc.medianBlur(Imgproc.java:7548)
	at Denoise.DenoiseFunc(Denoise.java:12)
	at LuckyProfileRunner.doLuckyProfileRunner(LuckyProfiler_.java:872)
	at LuckyProfileRunner.run(LuckyProfiler_.java:304)
Exception in thread "Thread-14" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.0) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\median_blur.dispatch.cpp:285: error: (-215:Assertion failed) (ksize % 2 == 1) && (_src0.dims() <= 2 ) in function 'cv::medianBlur'
]
	at org.opencv.imgproc.Imgproc.medianBlur_0(Native Method)
	at org.opencv.imgproc.Imgproc.medianBlur(Imgproc.java:7548)
	at Denoise.DenoiseFunc(Denoise.java:12)
	at LuckyProfileRunner.How2FWHM2Auto(LuckyProfiler_.java:343)
	at LuckyProfileRunner.run(LuckyProfiler_.java:307)

**Comment by Cyanotise** [comment]
Have u solved this？
